#!/bin/bash

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Service stoppen und deaktivieren
        systemctl stop checkmk-downtime.service || true
        systemctl disable checkmk-downtime.service || true

        # Systemd neu laden
        systemctl daemon-reload || true
        ;;
esac

exit 0
